# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='name',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
